name: .NET

on:
  push:
    branches: [ "master", "ap/publish-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*
    - name: Restore dependencies
      run: dotnet restore CsharpRAPL
    - name: Build
      run: dotnet build CsharpRAPL --no-restore
    - name: Test
      run: dotnet test CsharpRAPL --no-build --verbosity normal
    - name: Build Package
      run: dotnet pack CsharpRAPL --configuration Release
    - name: Push Package
      run: cd CsharpRAPL && dotnet nuget push "bin/Release/CsharpRAPL.*.nupkg" --api-key ${{secrets.PACKAGE_KEY}} --skip-duplicate --source "github"
